### ISSUE TITLE
Using it for personal website in CV navigation bar

### ISSUE THREAD

**Issue by vbhavsar16** [schochastics/classic-cv#2]
Hi David,
Thanks again for providing this great CV template.

I cloned your repo and when I preview it, I get a PDF web viewer. However, when I am linking the CV.qmd (containing your template) in _quarto.yml in the navbar tab "CV", I do not get the pdf web viewer. It generates the pdf but asks me to download it.

 My _quarto.yml
```
project:
  type: website

website:
  title: "Vivek Bhavsar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: notes.qmd
        text: Notes
      - href: CV.qmd
        text: CV
```
